version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: FullStack_rag
    ports:
      - \"5432:5432\"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - \"8000:8000\"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:12345@db:5432/FullStack_rag
      SECRET_KEY: mysecretkey123
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    volumes:
      - ./data:/app/data

volumes:
  pgdata:
